run sbt tasks individually and cache just before stage
This way the stage task can include slug-reduction while
still caching all the ivy downloads.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -89,22 +89,31 @@ HEROKU_PLUGIN="Heroku-0.11.3.scala"
 mkdir -p "$SBT_USER_HOME/.sbt/plugins"
 curl --silent --max-time 10 --location "http://s3.amazonaws.com/heroku-jvm-langpack-scala/$HEROKU_PLUGIN" --output "$SBT_USER_HOME/.sbt/plugins/$HEROKU_PLUGIN" --fail || error "Failed to download $HEROKU_PLUGIN"
 
-# build app
-echo "-----> Running: sbt $SBT_TASKS"
-test -e "$SBT_BINDIR"/sbt.boot.properties && PROPS_OPTION="-Dsbt.boot.properties=$SBT_BINDIR/sbt.boot.properties"
-HOME="$SBT_USER_HOME_ABSOLUTE" java -Xmx1024M -Dfile.encoding=UTF8 -Duser.home="$SBT_USER_HOME_ABSOLUTE" -Dsbt.log.noformat=true -Divy.default.ivy.user.dir="$SBT_USER_HOME_ABSOLUTE/.ivy2" $PROPS_OPTION -jar "$SBT_BINDIR"/$SBT_JAR $SBT_TASKS 2>&1 | sed -u 's/^/       /'
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  echo " !     Failed to build app with sbt"
-  exit 1
-fi
-
-# repack cache
-mkdir -p $CACHE_DIR
-for DIR in $CACHED_DIRS ; do
-  rm -rf $CACHE_DIR/$DIR
-  mkdir -p $CACHE_DIR/$DIR
-  if [ -d $DIR ] ; then
+function repack_cache {
+  echo "-----> Caching stuff in $CACHE_DIR for next time"
+  mkdir -p $CACHE_DIR
+  for DIR in $CACHED_DIRS ; do
+    rm -rf $CACHE_DIR/$DIR
+    mkdir -p $CACHE_DIR/$DIR
+    echo "----->     copying $DIR to $CACHE_DIR/$DIR"
     cp -r $DIR/.  $CACHE_DIR/$DIR
+  done
+}
+
+# build app
+for TASK in $SBT_TASKS ; do
+  if test x$TASK = xstage ; then
+    # repack cache just before staging, so the stage task
+    # can nuke stuff if needed
+    repack_cache
+  fi
+
+  echo "-----> Running: sbt $TASK"
+  test -e "$SBT_BINDIR"/sbt.boot.properties && PROPS_OPTION="-Dsbt.boot.properties=$SBT_BINDIR/sbt.boot.properties"
+  HOME="$SBT_USER_HOME_ABSOLUTE" java -Xmx1024M -Dfile.encoding=UTF8 -Duser.home="$SBT_USER_HOME_ABSOLUTE" -Dsbt.log.noformat=true -Divy.default.ivy.user.dir="$SBT_USER_HOME_ABSOLUTE/.ivy2" $PROPS_OPTION -jar "$SBT_BINDIR"/$SBT_JAR $TASK 2>&1 | sed -u 's/^/       /'
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to build app with sbt $SBT_VERSION"
+    exit 1
   fi
 done
 
